steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '-f', 'quickstart-docker/Dockerfile', './quickstart-docker' ]
images:
- 'gcr.io/$PROJECT_ID/quickstart-image'
